# Generated by Django 6.1.1 on 2026-09-27 02:26

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_requests_pending(apps, schema_editor):
    CustomerRequest = apps.get_model('orders', 'CustomerRequest')
    CustomerRequest.objects.filter(status__in=['', 'pending', 'PENDING']).update(status='Pending')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_supplier_purchase_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_request', to='orders.supplierorder'),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.RunPython(mark_existing_requests_pending, migrations.RunPython.noop),
    ]
